attempt to escape from garbage collector by: - using 'this' instead of 'sce.Main' inside sce.Main - declaring sce ns in overlay.js, and options.js - get TabsProgessListener definition out of sce.Main - call sce.Debug.init() using apply()
After a while, when accessing SCE-candidate sites, we would get:

Error: sce is not defined
Source File: chrome://sce/content/overlay.js
Line: 103

    26  sce.Main = {
...
   100    _getCertException: function(uri, cert) {
...
   103      var knownCert = sce.Main.overrideService.hasMatchingOverride(
...
   223    TabsProgressListener: {
...
   233      onSecurityChange: function (aBrowser, aWebProgress, aRequest, aState) {
...
   257        var knownCert = sce.Main._getCertException(uri, cert);

I'm unsure of the problem and the solutions though...